name: Deploy Unity3D Package

on: pull_request

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: check out latest commit
        uses: actions/checkout@v3
      - name: init script env
        run: source ./init.sh
      - name: run check-version script
        run: |
          chmod u+x ./scripts/check-version.py
          ./scripts/check-version.py