name: Check Code Lint

on: pull_request

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: check out latest commit
        uses: actions/checkout@v3
      - name: lint rust code
        run: cd ./ic-agent-ffi/ && cargo clippy -- -D warnings