name: Check Code Format

on: pull_request

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: check out latest commit
        uses: actions/checkout@v3
      - name: check rust code format
        run: cargo fmt --manifest-path ic-agent-ffi/Cargo.toml --check